///*
// * TryNN.java
// *
// * Created on __DATE__, __TIME__
// */
//
//package gui;
//
//import javax.swing.JFileChooser;
//import javax.swing.JOptionPane;
//
//import org.apache.log4j.helpers.FileWatchdog;
//
//import utilities.Matrix;
//import dataManager.Company;
//import architecture.Network;
//import architecture.Neuron;
//import dataManager.ReadExcel;
//import dataManager.ReadFile;
//
//
//
//
//
//
//import dataManager.WriteExcel;
//
////import jxl.read.biff.File; Esta libreria (la usada para gestionar la base de datos,  
////no vale para extensiones .csv (solo para extensiones excel extrictas (.xls)
////.csv no deja de ser un fichero de texto, lo leeremos como tal
//import java.io.File;
//import java.io.FileNotFoundException;
//import java.io.IOException;
//import java.math.BigDecimal;
//import java.util.ArrayList;
//
//import jxl.read.biff.BiffException;
//
////import jxl.Workbook;
////import jxl.read.biff.BiffException;
//
///**
// *
// * @author  __USER__
// */
//public class TryNN extends javax.swing.JFrame {
//
//	File fileWeightMatrix; //Estamos usando la libreria excel ( import .jxl) podríamos cambiarlo por 
//	//un simple import file y usar los tipos básicos de lectura
//	private String idCompany;
//	private int inicio, numPatrones, neuronSize;
//	private Matrix weightMatrix;
//
//	/** Creates new form TryNN */
//	public TryNN() {
//		initComponents();
//	}
//
//	/** This method is called from within the constructor to
//	 * initialize the form.
//	 * WARNING: Do NOT modify this code. The content of this method is
//	 * always regenerated by the Form Editor.
//	 */
//	//GEN-BEGIN:initComponents
//	// <editor-fold defaultstate="collapsed" desc="Generated Code">
//	private void initComponents() {
//
//		jLabel1 = new javax.swing.JLabel();
//		jLabel2 = new javax.swing.JLabel();
//		jLabel3 = new javax.swing.JLabel();
//		jLabel4 = new javax.swing.JLabel();
//		jLabel5 = new javax.swing.JLabel();
//		tfIdCompany = new javax.swing.JTextField();
//		jButton1 = new javax.swing.JButton();
//		tfInicio = new javax.swing.JTextField();
//		tfSizeNeuron = new javax.swing.JTextField();
//		tfNumPatrones = new javax.swing.JTextField();
//		jButton2 = new javax.swing.JButton();
//
//		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//		jLabel1.setText("Identificador empresa:");
//
//		jLabel2.setText("Matriz de pesos: ");
//
//		jLabel3.setText("Inicio inputs:  ");
//
//		jLabel4.setText("Tama\u00f1o inputs: ");
//
//		jLabel5.setText("N\u00ba inputs: ");
//
//		jButton1.setText("Seleccionar");
//		jButton1.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jButton1ActionPerformed(evt);
//			}
//		});
//
//		
//
//		jButton2.setText("Calcular Outputs");
//		jButton2.addActionListener(new java.awt.event.ActionListener() {
//			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				jButton2ActionPerformed(evt);
//			}
//		});
//
//		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
//				getContentPane());
//		getContentPane().setLayout(layout);
//		layout.setHorizontalGroup(layout
//				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(
//						layout.createSequentialGroup()
//								.addGap(49, 49, 49)
//								.addGroup(
//										layout.createParallelGroup(
//												javax.swing.GroupLayout.Alignment.LEADING)
//												.addComponent(jLabel5)
//												.addComponent(jLabel4)
//												.addGroup(
//														layout.createSequentialGroup()
//																.addComponent(
//																		jLabel1)
//																.addGap(18, 18,
//																		18)
//																.addComponent(
//																		tfIdCompany,
//																		javax.swing.GroupLayout.PREFERRED_SIZE,
//																		47,
//																		javax.swing.GroupLayout.PREFERRED_SIZE))
//												.addGroup(
//														layout.createSequentialGroup()
//																.addGroup(
//																		layout.createParallelGroup(
//																				javax.swing.GroupLayout.Alignment.LEADING)
//																				.addComponent(
//																						jLabel2)
//																				.addComponent(
//																						jLabel3))
//																.addGap(37, 37,
//																		37)
//																.addGroup(
//																		layout.createParallelGroup(
//																				javax.swing.GroupLayout.Alignment.LEADING)
//																				.addComponent(
//																						jButton1)
//																				.addGroup(
//																						layout.createSequentialGroup()
//																								.addGap(10,
//																										10,
//																										10)
//																								.addGroup(
//																										layout.createParallelGroup(
//																												javax.swing.GroupLayout.Alignment.LEADING,
//																												false)
//																												.addComponent(
//																														tfInicio,
//																														javax.swing.GroupLayout.DEFAULT_SIZE,
//																														42,
//																														Short.MAX_VALUE)
//																												.addComponent(
//																														tfSizeNeuron)
//																												.addComponent(
//																														tfNumPatrones))))))
//								.addContainerGap(140, Short.MAX_VALUE))
//				.addGroup(
//						javax.swing.GroupLayout.Alignment.TRAILING,
//						layout.createSequentialGroup()
//								.addContainerGap(274, Short.MAX_VALUE)
//								.addComponent(jButton2).addGap(55, 55, 55)));
//		layout.setVerticalGroup(layout
//				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//				.addGroup(
//						layout.createSequentialGroup()
//								.addGap(56, 56, 56)
//								.addGroup(
//										layout.createParallelGroup(
//												javax.swing.GroupLayout.Alignment.BASELINE)
//												.addComponent(jLabel1)
//												.addComponent(
//														tfIdCompany,
//														javax.swing.GroupLayout.PREFERRED_SIZE,
//														javax.swing.GroupLayout.DEFAULT_SIZE,
//														javax.swing.GroupLayout.PREFERRED_SIZE))
//								.addPreferredGap(
//										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//								.addGroup(
//										layout.createParallelGroup(
//												javax.swing.GroupLayout.Alignment.BASELINE)
//												.addComponent(jLabel2)
//												.addComponent(jButton1))
//								.addPreferredGap(
//										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//								.addGroup(
//										layout.createParallelGroup(
//												javax.swing.GroupLayout.Alignment.BASELINE)
//												.addComponent(jLabel3)
//												.addComponent(
//														tfInicio,
//														javax.swing.GroupLayout.PREFERRED_SIZE,
//														javax.swing.GroupLayout.DEFAULT_SIZE,
//														javax.swing.GroupLayout.PREFERRED_SIZE))
//								.addPreferredGap(
//										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//								.addGroup(
//										layout.createParallelGroup(
//												javax.swing.GroupLayout.Alignment.BASELINE)
//												.addComponent(jLabel4)
//												.addComponent(
//														tfSizeNeuron,
//														javax.swing.GroupLayout.PREFERRED_SIZE,
//														javax.swing.GroupLayout.DEFAULT_SIZE,
//														javax.swing.GroupLayout.PREFERRED_SIZE))
//								.addPreferredGap(
//										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//								.addGroup(
//										layout.createParallelGroup(
//												javax.swing.GroupLayout.Alignment.BASELINE)
//												.addComponent(jLabel5)
//												.addComponent(
//														tfNumPatrones,
//														javax.swing.GroupLayout.PREFERRED_SIZE,
//														javax.swing.GroupLayout.DEFAULT_SIZE,
//														javax.swing.GroupLayout.PREFERRED_SIZE))
//								.addPreferredGap(
//										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//								.addComponent(jButton2)
//								.addContainerGap(41, Short.MAX_VALUE)));
//
//		pack();
//	}// </editor-fold>
//	//GEN-END:initComponents
//
//	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
//		idCompany = tfIdCompany.getText();
//		if ( (idCompany == null) || (idCompany.equals("")) ){
//			JOptionPane.showMessageDialog(this,
//					"Error, el campo identificador de empresa está vacio",
//					"Campo requerido", JOptionPane.ERROR_MESSAGE);
//		}
//		
//		//Esto lo cambiaremos luego por una barra temporal, en la que se pueda seleccionar la fecha
//		String strInicio = tfInicio.getText();
//		inicio = Integer.parseInt(strInicio);
//		if ( (strInicio == null) || (strInicio.equals("")) ){
//			JOptionPane.showMessageDialog(this,
//					"Error, debes indicar donde empiezan los inputs", "Campo requerido", JOptionPane.ERROR_MESSAGE);
//		}
//		String strNumPatrones = tfNumPatrones.getText();
//		numPatrones = Integer.parseInt(strNumPatrones);
//		if ( (strNumPatrones == null) || (strNumPatrones.equals("")) ){
//			JOptionPane.showMessageDialog(this,
//					"Error, debes indicar el número de inputs", "Campo requerido", JOptionPane.ERROR_MESSAGE);
//		}
//		String strNeuronSize = tfSizeNeuron.getText();
//		neuronSize = Integer.parseInt(strNumPatrones);
//		if ( (strNeuronSize == null) || (strNeuronSize.equals("")) ){
//			JOptionPane.showMessageDialog(this,
//					"Error, debes indicar el tamaño de los inputs", "Campo requerido", JOptionPane.ERROR_MESSAGE);
//		}
//		
//		if (fileWeightMatrix == null){
//			JOptionPane.showMessageDialog(this,
//					"Error, debes seleccionar un archivo", "Archivo no seleccionado", JOptionPane.ERROR_MESSAGE);
//		}
//		
//		ReadExcel excel;
//			try {
//				excel = new ReadExcel();
//				Company p = excel.readCompanyById(idCompany);
//				Network n = Network.getInstance(p);
//				System.out.print("Id company: "+ idCompany+ " Número de inputs: "+ numPatrones+ " tamaño inputs: "+ neuronSize+ " Comenzando desde: "+ inicio + "/n");
//				System.out.print("Imprimimos matriz de pesos: \n");
//				weightMatrix.printMatrix();
//				ArrayList<Neuron>  inputs;
//				if (weightMatrix.getColumn() == weightMatrix.getRow()+1){ //La matriz procede de un entrenamiento con Bias
//					inputs = n.createArrayNeuronsRm(numPatrones, inicio, neuronSize, true);
//				}
//				else{
//					inputs = n.createArrayNeuronsRm(numPatrones, inicio, neuronSize, false);
//				}
//				ArrayList<Neuron> desiredOutputs = n.createArrayNeuronsRi(numPatrones, inicio, neuronSize); 
//				ArrayList<Neuron>  result = n.calculateOutputs(inputs, weightMatrix);
//				WriteExcel outfile = new WriteExcel("C:\\Users\\Esther\\Desktop\\Historial log\\tryNN\\results.csv");
//				outfile.writeGivenArrayNeuron(inputs, "Inputs: \n");
//				outfile.writeGivenArrayNeuron(result, "Outputs: \n");
//				outfile.writeGivenArrayNeuron(desiredOutputs, "Desired: \n");
//				outfile.closeFile();
//				
//				
//				
//			} catch (BiffException | IOException e) {
//				// TODO Auto-generated catch block
//				e.printStackTrace();
//			}
//	}
//
//
//	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//		JFileChooser filechooser = new JFileChooser(
//				"C:\\Users\\Esther\\Desktop\\Historial log\\actual");
//		int returnValue = filechooser.showOpenDialog(null);
//		if (returnValue == JFileChooser.APPROVE_OPTION) {
//			fileWeightMatrix = filechooser.getSelectedFile();
//			try {
//				ReadFile readWM = new ReadFile(fileWeightMatrix);
//				weightMatrix = readWM.readWeightMatrix();
//				
//						
//
//			} catch (FileNotFoundException e) {
//				// TODO Auto-generated catch block
//				e.printStackTrace();
//			}
//
//		} else {
//			System.out.println("Open command cancelled by user.");
//		}
//
//	}
//
//	/**
//	 * @param args the command line arguments
//	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new TryNN().setVisible(true);
//			}
//		});
//	}
//
//	//GEN-BEGIN:variables
//	// Variables declaration - do not modify
//	private javax.swing.JButton jButton1;
//	private javax.swing.JButton jButton2;
//	private javax.swing.JLabel jLabel1;
//	private javax.swing.JLabel jLabel2;
//	private javax.swing.JLabel jLabel3;
//	private javax.swing.JLabel jLabel4;
//	private javax.swing.JLabel jLabel5;
//	private javax.swing.JTextField tfIdCompany;
//	private javax.swing.JTextField tfInicio;
//	private javax.swing.JTextField tfNumPatrones;
//	private javax.swing.JTextField tfSizeNeuron;
//	// End of variables declaration//GEN-END:variables
//
//}